version: "3.8"

services:

  flask:
    build: ./back
    container_name: flasky
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    depends_on:
      - pgdb
    command: ["./wait-for-it.sh", "pgdb:5432", "--", "uwsgi", "app.ini"]

  nginx:
    build: ./nginx
    container_name: nginxy
    restart: always
    ports:
      - "80:80"

  pgdb:
    build: ./pgdb
    container_name: postgresy
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - "testy_pgdata:/var/lib/postgresql/data"

volumes:
  testy_pgdata:
