version: "3.8"

services:
  pgdb:
    build: ./pgdb
    container_name: psp_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=
    ports:
      - "5432"
    volumes:
      - "pspace_db:/var/lib/postgresql/data"

  redis:
    image: redis:6.0.8
    container_name: psp_redis
    restart: always
    ports:
      - "6379"

volumes:
  pspace_db:
